### ISSUE TITLE
Travis builds failing due to build timeouts

### ISSUE THREAD

**Issue by icyrockcom** [exercism/xpurescript#23]
Travis builds are failing due to build timeouts:

https://travis-ci.org/exercism/xpurescript/builds/209606731. 

The message is:

`The job exceeded the maximum time limit for jobs, and has been terminated.`

The above build took ~50m.

Chatted on gitter:

https://gitter.im/exercism/support?at=58c22a41872fc8ce62e00614

The recommendation is to start caching builds to shorten the build time, since `pulp` is recompiling everything every time.

**Comment by paf31** [comment]
We should be able to add `output/` to the Travis cache.

**Comment by icyrockcom** [comment]
Thanks Phil - with the additions in https://github.com/icyrockcom/xpurescript/commit/b2d0f0925725705053a79932236cd459710585ec the last [Travis build](https://travis-ci.org/icyrockcom/xpurescript/builds/209973237) now takes 7 mins (though without the latest word-count exercise that's pending approval) vs 21 / 23 / 24 / 34 mins.

This is a nice speed up, but not as much as I hoped so. Does it make sense to cache bower_components, too?

**Comment by paf31** [comment]
Yes, we can cache `bower_components`, but I'm not sure how much it will speed things up.

**Comment by icyrockcom** [comment]
[Latest build](https://travis-ci.org/icyrockcom/xpurescript/builds/209979402) of the above https://github.com/icyrockcom/xpurescript/commit/3226c6e472683a2f8612372b6bd119a3daa4322e finished in 3:39. While the variations are obviously great, this version promises to be perhaps 50-100% faster, so I'd go with it. If nothing else, there's less noise in the build logs.

**Comment by icyrockcom** [comment]
Any comments on this one or changes I should make? If this looks good, I can rebase on top of the current master for you to merge, let me know.

**Comment by lpil** [comment]
Looks good to me, thanks :)

**Comment by icyrockcom** [comment]
Thanks @lpil, rebased. The [build](https://travis-ci.org/icyrockcom/xpurescript/jobs/211151878) finished in 7:09, so quite slower than the other day, but still quite faster than current builds. For some reason, the project is being built even though it should be in the cache, e.g.:

```
-------------------------------------------------------
Testing accumulate
cache: lrwxrwxrwx 1 travis travis 56 Mar 14 22:59 bower_components -> /home/travis/.exercise_cache/accumulate/bower_components
cache: lrwxrwxrwx 1 travis travis 46 Mar 14 22:59 output -> /home/travis/.exercise_cache/accumulate/output
* Building project in /home/travis/build/icyrockcom/xpurescript/exercises/accumulate
Compiling Accumulate
Compiling Test.Main
```

so we are not getting the full speedup here. I could not reproduce locally, I'll have to look into it.

If you have a moment, please merge into master, as current builds are failing. For example, @paf31  merged word-count the other day, but the [build](https://travis-ci.org/exercism/xpurescript/builds/210089326) failed after 50 minutes.

**Comment by paf31** [comment]
Can you please make a PR?

**Comment by icyrockcom** [comment]
@paf31 Sure, https://github.com/exercism/xpurescript/pull/24

**Comment by icyrockcom** [comment]
Closed by https://github.com/exercism/xpurescript/pull/24
